language: go
go:
  - 1.12.4
os:
  - linux
  - osx
  - windows
env:
  - GO111MODULE=on
script:
  - diff -u <(echo -n) <(gofmt -d ./)
  - go test -short -cover -v -coverprofile=coverage.out -covermode=atomic ./...