language: go
go:
  - 1.12.4
env:
  global:
    - GO111MODULE=on
    - GOARCH=amd64
  matrix:
    - GOOS=linux
    - GOOS=darwin
    - GOOS=windows
script:
  - diff -u <(echo -n) <(gofmt -d ./)
  - go test -short -cover -v -coverprofile=coverage.out -covermode=atomic ./...